tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "git"
brew "go"
brew "python@3.9"
brew "httpie"
brew "neovim", args: ["HEAD"]
brew "node"
brew "postgresql"
cask "google-chrome"
cask "insomnia"
cask "iterm2"
cask "prisma-studio"
cask "visual-studio-code"
cask "zoom"
